[package]
name = "patcher"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FFXIV CN Patch Downloader"

[dependencies]
proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
md-5 = { workspace = true }
reqwest = { workspace = true }
quick-xml = { workspace = true }
encoding_rs = { workspace = true }
rsa = { workspace = true }
url = { workspace = true }
zip = { workspace = true }
rxdelta = { workspace = true }
time = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
